/**
 * GET /api/albums/:slug/download-urls
 *
 * Returns a JSON list of { name, url } for every published photo/video
 * in the album. The client-side downloader uses this list to fetch
 * files directly from the CDN and stream them into a ZIP (client-zip).
 *
 * Two storage backends:
 *   • Photos / small videos → Bunny Storage, served via /api/img proxy
 *     so we keep same-origin caching and access via API key.
 *   • Larger / transcoded videos → Bunny Stream, served directly from
 *     the Stream pull-zone CDN at /<videoId>/play_720p.mp4 (requires
 *     "Enable MP4 Fallback" in the Bunny Stream library settings).
 *     If that toggle isn't on, the CDN responds 404 and the client-zip
 *     downloader silently skips the file — the rest of the ZIP still
 *     builds correctly.
 *
 * Owner-only via checkAlbumOwnership (Clerk id OR verified-email match).
 */

import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import { albums, photos } from "@/lib/db/schema";
import { eq, and } from "drizzle-orm";
import { bunnyOriginalUrl } from "@/lib/storage/bunny";
import { checkAlbumOwnership } from "@/lib/album-ownership";

export const runtime = "nodejs";

const streamCdnUrl = () => process.env.BUNNY_STREAM_CDN_URL ?? "";

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ slug: string }> },
) {
  const { slug } = await params;

  const album = await db.query.albums.findFirst({ where: eq(albums.slug, slug) });
  if (!album) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const owner = await checkAlbumOwnership(album);
  if (!owner.ok) {
    return NextResponse.json({ error: owner.error }, { status: owner.status });
  }

  const albumPhotos = await db.query.photos.findMany({
    where: and(eq(photos.albumId, album.id), eq(photos.status, "published")),
    orderBy: (p, { asc }) => [asc(p.uploadedAt)],
  });

  let imgIdx = 1;
  let vidIdx = 1;
  const streamCdn = streamCdnUrl().replace(/\/+$/, "");

  // Build the file list. Order: photos first then videos (because client-zip
  // iterates sequentially and photos are typically smaller, so the ZIP starts
  // assembling fast and the user sees progress).
  const files: { name: string; url: string }[] = [];

  for (const photo of albumPhotos) {
    const isStreamVideo = !!photo.cfStreamVideoId;
    const isLocalVideo  = !isStreamVideo && (photo.mimeType?.startsWith("video/") ?? false);
    const isVideo       = isStreamVideo || isLocalVideo;

    let url: string | null = null;
    let extOverride: string | null = null;

    if (isStreamVideo) {
      // Bunny Stream MP4 fallback. Requires the library setting "Enable
      // MP4 Fallback" — if disabled, the CDN returns 404 and we skip
      // silently. 720p is generated by default and is the safest
      // resolution to ask for (every transcoded video has it).
      if (streamCdn) {
        url = `${streamCdn}/${photo.cfStreamVideoId}/play_720p.mp4`;
        extOverride = "mp4";
      } else {
        // No stream CDN configured — can't include this video.
        continue;
      }
    } else {
      url = bunnyOriginalUrl(photo.blobUrl);
    }

    if (!url) continue;

    const ext = extOverride
      ?? photo.mimeType?.split("/")[1]
      ?? (isVideo ? "mp4" : "jpg");
    const defaultName = isVideo
      ? `video-${String(vidIdx).padStart(3, "0")}.${ext}`
      : `foto-${String(imgIdx).padStart(3, "0")}.${ext}`;
    // For stream videos, replace the originalFilename's extension with
    // the actual mp4 we're delivering so the file opens correctly.
    let name = photo.originalFilename ?? defaultName;
    if (isStreamVideo) {
      name = name.replace(/\.[^.]+$/, "") + ".mp4";
    }

    if (isVideo) vidIdx++; else imgIdx++;

    files.push({
      name: isVideo ? `videos/${name}` : `photos/${name}`,
      url,
    });
  }

  return NextResponse.json({ files, albumName: album.coupleName, slug: album.slug });
}
