import type { Lang } from '@/lib/i18n/translations';
import type { WeddingRow } from './contracts';

const dictionaries = {
  "sl": {
    "plan": "Poročni premium",
    "nav": "Poročni paket",
    "eyebrow": "Več kot poročni album",
    "title": "Vajina poroka. Vsi gostje povezani.",
    "subtitle": "Fotografije, program, jedilnik, glasbene želje in fotografski bingo — na eni zasebni povezavi, brez aplikacije za goste.",
    "cta": "Začni brezplačno",
    "details": "Razišči poročni paket",
    "included": "Vse poročne funkcije vključene",
    "schedule": "Program poroke",
    "menu": "Jedilnik",
    "songs": "Glasbene želje",
    "bingo": "Fotografski bingo",
    "dj": "DJ-pult",
    "organiser": "Organizator",
    "guest": "Gost",
    "preview": "Predogled z vzorčnimi podatki",
    "save": "Shrani nastavitve",
    "saving": "Shranjujem …",
    "saved": "Nastavitve so shranjene.",
    "enabled": "Vključi poročne funkcije",
    "requestsOpen": "Sprejemaj glasbene želje",
    "add": "Dodaj",
    "remove": "Odstrani",
    "time": "Ura",
    "rowTitle": "Naslov",
    "rowDetail": "Opis / lokacija",
    "titleField": "Naslov skladbe",
    "artist": "Izvajalec",
    "name": "Tvoje ime",
    "note": "Sporočilo za DJ-ja (neobvezno)",
    "send": "Pošlji željo",
    "sent": "Želja je poslana DJ-ju.",
    "gallery": "Nazaj v galerijo",
    "upload": "Dodaj fotografijo",
    "refresh": "Osveži",
    "loading": "Nalagam …",
    "empty": "Za zdaj še ni vsebine.",
    "scheduleEmpty": "Organizator še pripravlja program.",
    "menuEmpty": "Jedilnik še ni objavljen.",
    "bingoEmpty": "Fotografski izzivi še niso objavljeni.",
    "new": "Nova",
    "accepted": "Sprejeta",
    "played": "Predvajana",
    "declined": "Zavrnjena",
    "mine": "Moj izziv je opravljen",
    "completed": "Fotografije gostov",
    "pendingNote": "Fotografija šteje kot opravljen izziv, ko jo organizator odobri.",
    "createDj": "Ustvari povezavo za DJ-ja",
    "copy": "Kopiraj",
    "copied": "Kopirano",
    "djHelp": "DJ vidi samo glasbene želje tega dogodka, ne administracije. Nova povezava prekliče prejšnjo.",
    "rotateConfirm": "Ustvarim novo povezavo? Prejšnja povezava za DJ-ja bo prenehala delovati.",
    "saveFirst": "Najprej shrani nastavitve.",
    "notPublished": "Album še ni objavljen. Objavi ga v nastavitvah albuma, da bodo gostje lahko odprli poročno stran.",
    "premiumRequired": "Poročne funkcije so vključene v paket Poročni premium.",
    "unavailable": "Poročne funkcije trenutno niso na voljo. Poskusi znova ali odpri galerijo.",
    "invalid": "Preveri obvezna polja, dolžino besedila in ure.",
    "forbidden": "Za to dejanje nimaš dovoljenja.",
    "signIn": "Za urejanje se prijavi.",
    "rateLimited": "Poslanih je preveč želja. Poskusi čez nekaj minut.",
    "requestsPaused": "DJ trenutno ne sprejema novih želja.",
    "refreshFirst": "Najprej osveži stran, nato poskusi znova.",
    "invalidDjLink": "Povezava za DJ-ja ni veljavna ali je bila preklicana.",
    "cancel": "Prekliči",
    "language": "Jezik",
    "play": "Predvajaj video",
    "pause": "Začasno ustavi",
    "mute": "Izklopi zvok",
    "unmute": "Vklopi zvok",
    "fullscreen": "Cel zaslon",
    "seek": "Položaj v videu",
    "videoLanguage": "Predstavitveni video v slovenščini",
    "videoTitle": "Poglejte GuestCam v akciji",
    "videoBody": "Gost skenira QR kodo, doda fotografije in spomini se zberejo v zasebni galeriji.",
    "setupHint": "Program, jedilnik in izzive urejaš tukaj. Spremembe se objavijo šele, ko jih shraniš.",
    "bingoHint": "Izberi izziv, dodaj fotografijo in sodeluj pri skupnem poročnem albumu.",
    "songHint": "Pošlji skladbo DJ-ju in spremljaj status svoje želje.",
    "sample": "Ana & Marko",
    "firstDance": "Prvi ples",
    "starters": "Predjed",
    "dessert": "Sladica",
    "menuHint": "Vpiši dejanski poročni jedilnik. Po potrebi dodaj alergene in prehranske možnosti.",
    "guestLink": "Odpri pogled za goste",
    "enableHint": "Gostje vidijo to stran le, ko je album objavljen in so poročne funkcije vključene.",
    "status": "Status",
    "error": "Prišlo je do napake. Poskusi znova.",
    "noSongs": "Glasbenih želja še ni.",
    "autoRefresh": "Samodejno osveževanje med odprtim DJ-pogledom",
    "manualRefresh": "Osveževanje se ustavi, ko skriješ zavihek.",
    "photoBingoFeatured": "Fotografski izzivi, ki povežejo goste",
    "challenges": [
      "Selfie z mladoporočencema",
      "Prvi ples",
      "Skupinska fotografija",
      "Nasmeh gosta",
      "Poročna torta",
      "Najboljši plesni gib",
      "Detajl dekoracije",
      "Nazdravljanje",
      "Iskren trenutek"
    ],
    "choose": "Izberi paket",
    "photosBenefit": "Neomejeno fotografij v originalni kakovosti",
    "videosBenefit": "Do 100 videoposnetkov",
    "storageBenefit": "Dostop do galerije 2 leti",
    "zipBenefit": "Prenos vseh datotek v ZIP",
    "wallBenefit": "Foto stena za TV ali projektor",
    "domainBenefit": "Lastna domena",
    "supportBenefit": "Prednostna podpora"
  },
  "hr": {
    "plan": "Vjenčani premium",
    "nav": "Vjenčani paket",
    "eyebrow": "Više od vjenčanog albuma",
    "title": "Vaše vjenčanje. Svi gosti povezani.",
    "subtitle": "Fotografije, raspored, jelovnik, glazbene želje i fotografski bingo — na jednoj privatnoj poveznici, bez aplikacije za goste.",
    "cta": "Isprobaj besplatno",
    "details": "Istraži vjenčani paket",
    "included": "Sve funkcije za vjenčanje su uključene",
    "schedule": "Raspored vjenčanja",
    "menu": "Jelovnik",
    "songs": "Glazbene želje",
    "bingo": "Fotografski bingo",
    "dj": "DJ-pult",
    "organiser": "Organizator",
    "guest": "Gost",
    "preview": "Pregled s oglednim podacima",
    "save": "Spremi postavke",
    "saving": "Spremanje …",
    "saved": "Postavke su spremljene.",
    "enabled": "Uključi vjenčane značajke",
    "requestsOpen": "Primaj glazbene želje",
    "add": "Dodaj",
    "remove": "Ukloni",
    "time": "Vrijeme",
    "rowTitle": "Naslov",
    "rowDetail": "Opis / lokacija",
    "titleField": "Naslov pjesme",
    "artist": "Izvođač",
    "name": "Tvoje ime",
    "note": "Poruka za DJ-a (neobavezno)",
    "send": "Pošalji želju",
    "sent": "Želja je poslana DJ-u.",
    "gallery": "Natrag u galeriju",
    "upload": "Dodaj fotografiju",
    "refresh": "Osvježi",
    "loading": "Učitavanje …",
    "empty": "Još nema sadržaja.",
    "scheduleEmpty": "Organizator još priprema raspored.",
    "menuEmpty": "Jelovnik još nije objavljen.",
    "bingoEmpty": "Fotografski izazovi još nisu objavljeni.",
    "new": "Nova",
    "accepted": "Prihvaćena",
    "played": "Odsvirana",
    "declined": "Odbijena",
    "mine": "Moj je izazov dovršen",
    "completed": "Fotografije gostiju",
    "pendingNote": "Fotografija se računa kao dovršen izazov nakon što je organizator odobri.",
    "createDj": "Izradi poveznicu za DJ-a",
    "copy": "Kopiraj",
    "copied": "Kopirano",
    "djHelp": "DJ vidi samo glazbene želje ovog događaja, ne administraciju. Nova poveznica poništava prethodnu.",
    "rotateConfirm": "Izraditi novu poveznicu? Prethodna poveznica za DJ-a prestat će raditi.",
    "saveFirst": "Najprije spremi postavke.",
    "notPublished": "Album još nije objavljen. Objavi ga u postavkama albuma kako bi gosti mogli otvoriti vjenčanu stranicu.",
    "premiumRequired": "Vjenčane značajke uključene su u paket Vjenčani premium.",
    "unavailable": "Vjenčane značajke trenutno nisu dostupne. Pokušaj ponovno ili otvori galeriju.",
    "invalid": "Provjeri obavezna polja, duljinu teksta i vrijeme.",
    "forbidden": "Nemaš dopuštenje za ovu radnju.",
    "signIn": "Prijavi se za uređivanje.",
    "rateLimited": "Poslano je previše želja. Pokušaj za nekoliko minuta.",
    "requestsPaused": "DJ trenutačno ne prima nove želje.",
    "refreshFirst": "Najprije osvježi stranicu i pokušaj ponovno.",
    "invalidDjLink": "Poveznica za DJ-a nije valjana ili je opozvana.",
    "cancel": "Odustani",
    "language": "Jezik",
    "play": "Reproduciraj video",
    "pause": "Pauziraj",
    "mute": "Isključi zvuk",
    "unmute": "Uključi zvuk",
    "fullscreen": "Cijeli zaslon",
    "seek": "Položaj u videu",
    "videoLanguage": "Predstavni video na slovenskom",
    "videoTitle": "Pogledajte GuestCam na djelu",
    "videoBody": "Gost skenira QR kod, dodaje fotografije i uspomene se okupljaju u privatnoj galeriji.",
    "setupHint": "Ovdje uređuješ raspored, jelovnik i izazove. Promjene se objavljuju tek nakon spremanja.",
    "bingoHint": "Odaberi izazov, dodaj fotografiju i sudjeluj u zajedničkom vjenčanom albumu.",
    "songHint": "Pošalji pjesmu DJ-u i prati status svoje želje.",
    "sample": "Ana & Marko",
    "firstDance": "Prvi ples",
    "starters": "Predjelo",
    "dessert": "Desert",
    "menuHint": "Unesi stvarni vjenčani jelovnik. Po potrebi dodaj alergene i prehrambene mogućnosti.",
    "guestLink": "Otvori prikaz za goste",
    "enableHint": "Gosti vide ovu stranicu samo kada je album objavljen i vjenčane značajke uključene.",
    "status": "Status",
    "error": "Došlo je do pogreške. Pokušaj ponovno.",
    "noSongs": "Još nema glazbenih želja.",
    "autoRefresh": "Automatsko osvježavanje dok je DJ-prikaz otvoren",
    "manualRefresh": "Osvježavanje se zaustavlja kada sakriješ karticu.",
    "photoBingoFeatured": "Fotografski izazovi koji povezuju goste",
    "challenges": [
      "Selfie s mladencima",
      "Prvi ples",
      "Zajednička fotografija",
      "Osmijeh gosta",
      "Vjenčana torta",
      "Najbolji plesni pokret",
      "Detalj dekoracije",
      "Zdravica",
      "Spontani trenutak"
    ],
    "choose": "Odaberi paket",
    "photosBenefit": "Neograničeno fotografija u izvornoj kvaliteti",
    "videosBenefit": "Do 100 videozapisa",
    "storageBenefit": "Pristup galeriji 2 godine",
    "zipBenefit": "Preuzimanje svih datoteka u ZIP-u",
    "wallBenefit": "Foto zid za TV ili projektor",
    "domainBenefit": "Vlastita domena",
    "supportBenefit": "Prioritetna podrška"
  },
  "sr": {
    "plan": "Venčani premium",
    "nav": "Venčani paket",
    "eyebrow": "Više od venčanog albuma",
    "title": "Vaše venčanje. Svi gosti povezani.",
    "subtitle": "Fotografije, raspored, jelovnik, muzičke želje i fotografski bingo — na jednom privatnom linku, bez aplikacije za goste.",
    "cta": "Isprobaj besplatno",
    "details": "Istraži venčani paket",
    "included": "Sve funkcije za venčanje su uključene",
    "schedule": "Raspored venčanja",
    "menu": "Jelovnik",
    "songs": "Muzičke želje",
    "bingo": "Fotografski bingo",
    "dj": "DJ-pult",
    "organiser": "Organizator",
    "guest": "Gost",
    "preview": "Pregled sa primerima podataka",
    "save": "Sačuvaj podešavanja",
    "saving": "Čuvanje …",
    "saved": "Podešavanja su sačuvana.",
    "enabled": "Uključi venčane funkcije",
    "requestsOpen": "Primaj muzičke želje",
    "add": "Dodaj",
    "remove": "Ukloni",
    "time": "Vreme",
    "rowTitle": "Naslov",
    "rowDetail": "Opis / lokacija",
    "titleField": "Naziv pesme",
    "artist": "Izvođač",
    "name": "Tvoje ime",
    "note": "Poruka za DJ-a (neobavezno)",
    "send": "Pošalji želju",
    "sent": "Želja je poslata DJ-u.",
    "gallery": "Nazad u galeriju",
    "upload": "Dodaj fotografiju",
    "refresh": "Osveži",
    "loading": "Učitavanje …",
    "empty": "Još nema sadržaja.",
    "scheduleEmpty": "Organizator još priprema raspored.",
    "menuEmpty": "Jelovnik još nije objavljen.",
    "bingoEmpty": "Fotografski izazovi još nisu objavljeni.",
    "new": "Nova",
    "accepted": "Prihvaćena",
    "played": "Puštena",
    "declined": "Odbijena",
    "mine": "Moj izazov je završen",
    "completed": "Fotografije gostiju",
    "pendingNote": "Fotografija se računa kao završen izazov nakon što je organizator odobri.",
    "createDj": "Napravi link za DJ-a",
    "copy": "Kopiraj",
    "copied": "Kopirano",
    "djHelp": "DJ vidi samo muzičke želje ovog događaja, ne administraciju. Novi link poništava prethodni.",
    "rotateConfirm": "Napraviti novi link? Prethodni link za DJ-a će prestati da radi.",
    "saveFirst": "Prvo sačuvaj podešavanja.",
    "notPublished": "Album još nije objavljen. Objavi ga u podešavanjima albuma kako bi gosti mogli da otvore venčanu stranicu.",
    "premiumRequired": "Venčane funkcije su uključene u paket Venčani premium.",
    "unavailable": "Venčane funkcije trenutno nisu dostupne. Pokušaj ponovo ili otvori galeriju.",
    "invalid": "Proveri obavezna polja, dužinu teksta i vreme.",
    "forbidden": "Nemaš dozvolu za ovu radnju.",
    "signIn": "Prijavi se za uređivanje.",
    "rateLimited": "Poslato je previše želja. Pokušaj za nekoliko minuta.",
    "requestsPaused": "DJ trenutno ne prima nove želje.",
    "refreshFirst": "Prvo osveži stranicu i pokušaj ponovo.",
    "invalidDjLink": "Link za DJ-a nije važeći ili je opozvan.",
    "cancel": "Otkaži",
    "language": "Jezik",
    "play": "Pusti video",
    "pause": "Pauziraj",
    "mute": "Isključi zvuk",
    "unmute": "Uključi zvuk",
    "fullscreen": "Ceo ekran",
    "seek": "Položaj u videu",
    "videoLanguage": "Predstavni video na slovenačkom",
    "videoTitle": "Pogledajte GuestCam na delu",
    "videoBody": "Gost skenira QR kod, dodaje fotografije i uspomene se okupljaju u privatnoj galeriji.",
    "setupHint": "Ovde uređuješ raspored, jelovnik i izazove. Promene se objavljuju tek nakon čuvanja.",
    "bingoHint": "Izaberi izazov, dodaj fotografiju i učestvuj u zajedničkom venčanom albumu.",
    "songHint": "Pošalji pesmu DJ-u i prati status svoje želje.",
    "sample": "Ana & Marko",
    "firstDance": "Prvi ples",
    "starters": "Predjelo",
    "dessert": "Dezert",
    "menuHint": "Unesi stvarni venčani jelovnik. Po potrebi dodaj alergene i opcije ishrane.",
    "guestLink": "Otvori prikaz za goste",
    "enableHint": "Gosti vide ovu stranicu samo kada je album objavljen i venčane funkcije uključene.",
    "status": "Status",
    "error": "Došlo je do greške. Pokušaj ponovo.",
    "noSongs": "Još nema muzičkih želja.",
    "autoRefresh": "Automatsko osvežavanje dok je DJ-prikaz otvoren",
    "manualRefresh": "Osvežavanje se zaustavlja kada sakriješ karticu.",
    "photoBingoFeatured": "Fotografski izazovi koji povezuju goste",
    "challenges": [
      "Selfi sa mladencima",
      "Prvi ples",
      "Zajednička fotografija",
      "Osmeh gosta",
      "Venčana torta",
      "Najbolji plesni pokret",
      "Detalj dekoracije",
      "Zdravica",
      "Spontani trenutak"
    ],
    "choose": "Izaberi paket",
    "photosBenefit": "Neograničeno fotografija u originalnom kvalitetu",
    "videosBenefit": "Do 100 video snimaka",
    "storageBenefit": "Pristup galeriji 2 godine",
    "zipBenefit": "Preuzimanje svih datoteka u ZIP-u",
    "wallBenefit": "Foto zid za TV ili projektor",
    "domainBenefit": "Sopstveni domen",
    "supportBenefit": "Prioritetna podrška"
  },
  "en": {
    "plan": "Wedding Premium",
    "nav": "Wedding package",
    "eyebrow": "More than a wedding album",
    "title": "Your wedding. Every guest connected.",
    "subtitle": "Photos, schedule, menu, song requests and photo bingo — one private link, with no app for your guests.",
    "cta": "Try for free",
    "details": "Explore the wedding package",
    "included": "All wedding features included",
    "schedule": "Wedding schedule",
    "menu": "Menu",
    "songs": "Song requests",
    "bingo": "Photo bingo",
    "dj": "DJ desk",
    "organiser": "Organiser",
    "guest": "Guest",
    "preview": "Preview with sample data",
    "save": "Save settings",
    "saving": "Saving …",
    "saved": "Settings saved.",
    "enabled": "Enable wedding features",
    "requestsOpen": "Accept song requests",
    "add": "Add",
    "remove": "Remove",
    "time": "Time",
    "rowTitle": "Title",
    "rowDetail": "Description / location",
    "titleField": "Song title",
    "artist": "Artist",
    "name": "Your name",
    "note": "Message for the DJ (optional)",
    "send": "Send request",
    "sent": "Your request was sent to the DJ.",
    "gallery": "Back to gallery",
    "upload": "Add a photo",
    "refresh": "Refresh",
    "loading": "Loading …",
    "empty": "No content yet.",
    "scheduleEmpty": "The organiser is still preparing the schedule.",
    "menuEmpty": "The menu has not been published yet.",
    "bingoEmpty": "Photo challenges have not been published yet.",
    "new": "New",
    "accepted": "Accepted",
    "played": "Played",
    "declined": "Declined",
    "mine": "My challenge is complete",
    "completed": "Guest photos",
    "pendingNote": "A photo counts as a completed challenge once the organiser approves it.",
    "createDj": "Create DJ link",
    "copy": "Copy",
    "copied": "Copied",
    "djHelp": "The DJ sees only this event’s song requests, not the admin dashboard. A new link revokes the previous one.",
    "rotateConfirm": "Create a new link? The previous DJ link will stop working.",
    "saveFirst": "Save the settings first.",
    "notPublished": "This album is not published yet. Publish it in album settings so guests can open the wedding page.",
    "premiumRequired": "Wedding features are included in Wedding Premium.",
    "unavailable": "Wedding features are currently unavailable. Try again or open the gallery.",
    "invalid": "Check required fields, text lengths and times.",
    "forbidden": "You do not have permission for this action.",
    "signIn": "Sign in to edit.",
    "rateLimited": "Too many requests. Please try again in a few minutes.",
    "requestsPaused": "The DJ is not accepting new requests right now.",
    "refreshFirst": "Refresh the page first, then try again.",
    "invalidDjLink": "This DJ link is invalid or has been revoked.",
    "cancel": "Cancel",
    "language": "Language",
    "play": "Play video",
    "pause": "Pause",
    "mute": "Mute",
    "unmute": "Unmute",
    "fullscreen": "Full screen",
    "seek": "Video position",
    "videoLanguage": "Promotional video in Slovenian",
    "videoTitle": "See GuestCam in action",
    "videoBody": "A guest scans the QR code, adds photos and memories come together in your private gallery.",
    "setupHint": "Edit your schedule, menu and challenges here. Changes are published only after you save them.",
    "bingoHint": "Choose a challenge, add a photo and contribute to the shared wedding album.",
    "songHint": "Send a song to the DJ and check the status of your request.",
    "sample": "Ana & Marko",
    "firstDance": "First dance",
    "starters": "Starter",
    "dessert": "Dessert",
    "menuHint": "Enter your actual wedding menu. Add allergens and dietary options where appropriate.",
    "guestLink": "Open guest view",
    "enableHint": "Guests see this page only when the album is published and wedding features are enabled.",
    "status": "Status",
    "error": "Something went wrong. Please try again.",
    "noSongs": "No song requests yet.",
    "autoRefresh": "Automatic refresh while the DJ view is open",
    "manualRefresh": "Refreshing stops when the tab is hidden.",
    "photoBingoFeatured": "Photo challenges that bring guests together",
    "challenges": [
      "Selfie with the couple",
      "First dance",
      "Group photo",
      "A guest’s smile",
      "Wedding cake",
      "Best dance move",
      "A decoration detail",
      "The toast",
      "A candid moment"
    ],
    "choose": "Choose package",
    "photosBenefit": "Unlimited original-quality photos",
    "videosBenefit": "Up to 100 videos",
    "storageBenefit": "2 years of gallery access",
    "zipBenefit": "Download every file as a ZIP",
    "wallBenefit": "Photo Wall for TV or projector",
    "domainBenefit": "Custom domain",
    "supportBenefit": "Priority support"
  },
  "de": {
    "plan": "Hochzeits-Premium",
    "nav": "Hochzeitspaket",
    "eyebrow": "Mehr als ein Hochzeitsalbum",
    "title": "Eure Hochzeit. Alle Gäste verbunden.",
    "subtitle": "Fotos, Ablauf, Menü, Musikwünsche und Foto-Bingo — über einen privaten Link, ohne App für eure Gäste.",
    "cta": "Kostenlos testen",
    "details": "Hochzeitspaket entdecken",
    "included": "Alle Hochzeitsfunktionen inklusive",
    "schedule": "Hochzeitsablauf",
    "menu": "Menü",
    "songs": "Musikwünsche",
    "bingo": "Foto-Bingo",
    "dj": "DJ-Pult",
    "organiser": "Veranstalter",
    "guest": "Gast",
    "preview": "Vorschau mit Beispieldaten",
    "save": "Einstellungen speichern",
    "saving": "Wird gespeichert …",
    "saved": "Einstellungen gespeichert.",
    "enabled": "Hochzeitsfunktionen aktivieren",
    "requestsOpen": "Musikwünsche annehmen",
    "add": "Hinzufügen",
    "remove": "Entfernen",
    "time": "Uhrzeit",
    "rowTitle": "Titel",
    "rowDetail": "Beschreibung / Ort",
    "titleField": "Songtitel",
    "artist": "Interpret",
    "name": "Dein Name",
    "note": "Nachricht an den DJ (optional)",
    "send": "Wunsch senden",
    "sent": "Dein Wunsch wurde an den DJ gesendet.",
    "gallery": "Zurück zur Galerie",
    "upload": "Foto hinzufügen",
    "refresh": "Aktualisieren",
    "loading": "Wird geladen …",
    "empty": "Noch keine Inhalte.",
    "scheduleEmpty": "Der Veranstalter bereitet den Ablauf noch vor.",
    "menuEmpty": "Das Menü wurde noch nicht veröffentlicht.",
    "bingoEmpty": "Fotoaufgaben wurden noch nicht veröffentlicht.",
    "new": "Neu",
    "accepted": "Angenommen",
    "played": "Gespielt",
    "declined": "Abgelehnt",
    "mine": "Meine Aufgabe ist erledigt",
    "completed": "Gästefotos",
    "pendingNote": "Ein Foto zählt als erledigte Aufgabe, sobald der Veranstalter es freigegeben hat.",
    "createDj": "DJ-Link erstellen",
    "copy": "Kopieren",
    "copied": "Kopiert",
    "djHelp": "Der DJ sieht nur die Musikwünsche dieses Events, nicht die Verwaltung. Ein neuer Link ersetzt den bisherigen.",
    "rotateConfirm": "Neuen Link erstellen? Der bisherige DJ-Link funktioniert danach nicht mehr.",
    "saveFirst": "Speichere zuerst die Einstellungen.",
    "notPublished": "Dieses Album ist noch nicht veröffentlicht. Veröffentliche es in den Albumeinstellungen, damit Gäste die Hochzeitsseite öffnen können.",
    "premiumRequired": "Hochzeitsfunktionen sind in Hochzeits-Premium enthalten.",
    "unavailable": "Die Hochzeitsfunktionen sind derzeit nicht verfügbar. Versuche es erneut oder öffne die Galerie.",
    "invalid": "Prüfe Pflichtfelder, Textlängen und Uhrzeiten.",
    "forbidden": "Du hast keine Berechtigung für diese Aktion.",
    "signIn": "Zum Bearbeiten anmelden.",
    "rateLimited": "Zu viele Wünsche. Versuche es in einigen Minuten erneut.",
    "requestsPaused": "Der DJ nimmt gerade keine neuen Wünsche an.",
    "refreshFirst": "Aktualisiere zuerst die Seite und versuche es erneut.",
    "invalidDjLink": "Dieser DJ-Link ist ungültig oder wurde widerrufen.",
    "cancel": "Abbrechen",
    "language": "Sprache",
    "play": "Video abspielen",
    "pause": "Pausieren",
    "mute": "Ton aus",
    "unmute": "Ton an",
    "fullscreen": "Vollbild",
    "seek": "Videoposition",
    "videoLanguage": "Vorstellungsvideo auf Slowenisch",
    "videoTitle": "GuestCam in Aktion erleben",
    "videoBody": "Ein Gast scannt den QR-Code, fügt Fotos hinzu und alle Erinnerungen landen in eurer privaten Galerie.",
    "setupHint": "Bearbeite hier Ablauf, Menü und Aufgaben. Änderungen werden erst nach dem Speichern veröffentlicht.",
    "bingoHint": "Wähle eine Aufgabe, füge ein Foto hinzu und gestalte das gemeinsame Hochzeitsalbum mit.",
    "songHint": "Sende einen Song an den DJ und verfolge den Status deines Wunsches.",
    "sample": "Ana & Marko",
    "firstDance": "Erster Tanz",
    "starters": "Vorspeise",
    "dessert": "Dessert",
    "menuHint": "Trage das tatsächliche Hochzeitsmenü ein. Ergänze bei Bedarf Allergene und Ernährungsoptionen.",
    "guestLink": "Gästeansicht öffnen",
    "enableHint": "Gäste sehen diese Seite nur, wenn das Album veröffentlicht ist und die Hochzeitsfunktionen aktiviert sind.",
    "status": "Status",
    "error": "Ein Fehler ist aufgetreten. Versuche es erneut.",
    "noSongs": "Noch keine Musikwünsche.",
    "autoRefresh": "Automatische Aktualisierung bei geöffneter DJ-Ansicht",
    "manualRefresh": "Die Aktualisierung pausiert bei verborgenem Tab.",
    "photoBingoFeatured": "Fotoaufgaben, die Gäste zusammenbringen",
    "challenges": [
      "Selfie mit dem Brautpaar",
      "Erster Tanz",
      "Gruppenfoto",
      "Das Lächeln eines Gastes",
      "Hochzeitstorte",
      "Bester Tanzschritt",
      "Ein Dekorationsdetail",
      "Der Toast",
      "Ein spontaner Moment"
    ],
    "choose": "Paket auswählen",
    "photosBenefit": "Unbegrenzte Fotos in Originalqualität",
    "videosBenefit": "Bis zu 100 Videos",
    "storageBenefit": "2 Jahre Galerie-Zugriff",
    "zipBenefit": "Alle Dateien als ZIP herunterladen",
    "wallBenefit": "Fotowand für TV oder Beamer",
    "domainBenefit": "Eigene Domain",
    "supportBenefit": "Bevorzugter Support"
  },
  "es": {
    "plan": "Premium para bodas",
    "nav": "Paquete para bodas",
    "eyebrow": "Más que un álbum de boda",
    "title": "Vuestra boda. Todos los invitados conectados.",
    "subtitle": "Fotos, programa, menú, peticiones musicales y bingo fotográfico — un enlace privado, sin aplicaciones para los invitados.",
    "cta": "Probar gratis",
    "details": "Descubrir el paquete para bodas",
    "included": "Todas las funciones para bodas incluidas",
    "schedule": "Programa de la boda",
    "menu": "Menú",
    "songs": "Peticiones musicales",
    "bingo": "Bingo fotográfico",
    "dj": "Panel del DJ",
    "organiser": "Organizador",
    "guest": "Invitado",
    "preview": "Vista previa con datos de ejemplo",
    "save": "Guardar ajustes",
    "saving": "Guardando …",
    "saved": "Ajustes guardados.",
    "enabled": "Activar funciones para bodas",
    "requestsOpen": "Aceptar peticiones musicales",
    "add": "Añadir",
    "remove": "Eliminar",
    "time": "Hora",
    "rowTitle": "Título",
    "rowDetail": "Descripción / lugar",
    "titleField": "Título de la canción",
    "artist": "Artista",
    "name": "Tu nombre",
    "note": "Mensaje para el DJ (opcional)",
    "send": "Enviar petición",
    "sent": "Tu petición se ha enviado al DJ.",
    "gallery": "Volver a la galería",
    "upload": "Añadir una foto",
    "refresh": "Actualizar",
    "loading": "Cargando …",
    "empty": "Todavía no hay contenido.",
    "scheduleEmpty": "El organizador está preparando el programa.",
    "menuEmpty": "El menú aún no se ha publicado.",
    "bingoEmpty": "Los retos fotográficos aún no se han publicado.",
    "new": "Nueva",
    "accepted": "Aceptada",
    "played": "Reproducida",
    "declined": "Rechazada",
    "mine": "Mi reto está completado",
    "completed": "Fotos de los invitados",
    "pendingNote": "La foto cuenta como reto completado cuando el organizador la aprueba.",
    "createDj": "Crear enlace para el DJ",
    "copy": "Copiar",
    "copied": "Copiado",
    "djHelp": "El DJ solo ve las peticiones de este evento, no la administración. Un enlace nuevo anula el anterior.",
    "rotateConfirm": "¿Crear un enlace nuevo? El enlace anterior del DJ dejará de funcionar.",
    "saveFirst": "Guarda primero los ajustes.",
    "notPublished": "El álbum aún no está publicado. Publícalo en sus ajustes para que los invitados puedan abrir la página de la boda.",
    "premiumRequired": "Las funciones para bodas están incluidas en Premium para bodas.",
    "unavailable": "Las funciones para bodas no están disponibles ahora. Inténtalo de nuevo o abre la galería.",
    "invalid": "Revisa los campos obligatorios, la longitud del texto y las horas.",
    "forbidden": "No tienes permiso para esta acción.",
    "signIn": "Inicia sesión para editar.",
    "rateLimited": "Demasiadas peticiones. Inténtalo de nuevo en unos minutos.",
    "requestsPaused": "El DJ no acepta nuevas peticiones en este momento.",
    "refreshFirst": "Actualiza primero la página e inténtalo de nuevo.",
    "invalidDjLink": "El enlace del DJ no es válido o ha sido revocado.",
    "cancel": "Cancelar",
    "language": "Idioma",
    "play": "Reproducir vídeo",
    "pause": "Pausar",
    "mute": "Silenciar",
    "unmute": "Activar sonido",
    "fullscreen": "Pantalla completa",
    "seek": "Posición del vídeo",
    "videoLanguage": "Vídeo de presentación en esloveno",
    "videoTitle": "Descubre GuestCam en acción",
    "videoBody": "Un invitado escanea el QR, añade fotos y los recuerdos se reúnen en vuestra galería privada.",
    "setupHint": "Edita aquí el programa, el menú y los retos. Los cambios solo se publican al guardarlos.",
    "bingoHint": "Elige un reto, añade una foto y participa en el álbum compartido de la boda.",
    "songHint": "Envía una canción al DJ y consulta el estado de tu petición.",
    "sample": "Ana & Marko",
    "firstDance": "Primer baile",
    "starters": "Entrante",
    "dessert": "Postre",
    "menuHint": "Introduce el menú real de la boda. Añade alérgenos y opciones alimentarias cuando corresponda.",
    "guestLink": "Abrir vista de invitados",
    "enableHint": "Los invitados ven esta página solo cuando el álbum está publicado y las funciones para bodas están activadas.",
    "status": "Estado",
    "error": "Se ha producido un error. Inténtalo de nuevo.",
    "noSongs": "Aún no hay peticiones musicales.",
    "autoRefresh": "Actualización automática con el panel del DJ abierto",
    "manualRefresh": "La actualización se detiene cuando ocultas la pestaña.",
    "photoBingoFeatured": "Retos fotográficos que unen a los invitados",
    "challenges": [
      "Selfie con la pareja",
      "Primer baile",
      "Foto de grupo",
      "La sonrisa de un invitado",
      "Tarta de boda",
      "El mejor paso de baile",
      "Un detalle de la decoración",
      "El brindis",
      "Un momento espontáneo"
    ],
    "choose": "Elegir paquete",
    "photosBenefit": "Fotos ilimitadas en calidad original",
    "videosBenefit": "Hasta 100 vídeos",
    "storageBenefit": "Acceso a la galería durante 2 años",
    "zipBenefit": "Descarga de todos los archivos en ZIP",
    "wallBenefit": "Muro de fotos para TV o proyector",
    "domainBenefit": "Dominio propio",
    "supportBenefit": "Soporte prioritario"
  }
};
export type WeddingCopy = typeof dictionaries.sl;
export const WEDDING_COPY: Record<Lang, WeddingCopy> = dictionaries;
export function weddingCopy(lang: Lang) { return WEDDING_COPY[lang]; }
export function weddingError(lang: Lang, code: unknown) { const copy = weddingCopy(lang); const value = typeof code === 'string' ? copy[code as keyof WeddingCopy] : null; return typeof value === 'string' ? value : copy.error; }
export function defaultChallenges(lang: Lang): WeddingRow[] { return weddingCopy(lang).challenges.map((title, i) => ({id: `challenge-${i+1}`, title, detail: ''})); }
