import type { PrintShowroomCopy } from "@/components/PrintShowroom";
import type { BusinessCopy } from "@/components/BusinessSection";

/**
 * Copy for the print-showroom and for-business homepage sections, all six
 * languages in one place so the SL page (app/page.tsx) and the localized
 * homepages render identical sections from the same source of truth.
 */

export type SectionLang = "sl" | "hr" | "sr" | "de" | "en" | "es";

export const NAV_BUSINESS: Record<SectionLang, string> = {
  sl: "Podjetja",
  hr: "Za tvrtke",
  sr: "Za firme",
  de: "Für Firmen",
  en: "For business",
  es: "Empresas",
};

export const PRINT_COPY: Record<SectionLang, PrintShowroomCopy> = {
  sl: {
    badge: "Predloge za tisk",
    title: "Zberite vsak trenutek.",
    accentTitle: "Podoživite jih za vedno.",
    body: "Dodajte QR kodo na mize in omogočite gostom, da v eni čudoviti galeriji delijo fotografije in videe.",
    bullets: ["Postavitev v 3 korakih", "Brez aplikacije", "Brezplačen preizkus", "Brez prijave za goste"],
    cta: "Ustvari galerijo in QR kodo →",
    designCta: "Poglej dizajne kartic",
    note: (p) => `Tiskani podstavki od ${p}/kos · naročite vsaj 10 dni pred dogodkom`,
    woodName: "Leseni podstavek", goldName: "Zlati podstavek", perPiece: " / kos",
    imageAlts: [
      "Guestcam QR kartice za deljenje fotografij na dogodku",
      "Galerija fotografij Guestcam, prikazana na telefonu gosta",
      "Zlati namizni podstavek z Guestcam QR kodo",
      "Gost uporablja Guestcam za ogled fotografij dogodka na telefonu",
    ],
    statusPhoto: "Skeniraj in deli",
    statusUpload: "Nalaganje končano!",
    statusLive: "Slideshow v živo",
    statusNew: "Nova slika dodana",
    trustLine: "Ustvarjeno za prave trenutke · Zasebno in varno",
  },
  hr: {
    badge: "Predlošci za tisak",
    title: "Sačuvajte svaki trenutak.",
    accentTitle: "Proživite ih ponovno.",
    body: "Dodajte QR kod na stolove i omogućite gostima da fotografije i videozapise dijele u jednoj prekrasnoj galeriji.",
    bullets: ["Postavljanje u 3 koraka", "Bez aplikacije", "Besplatna proba", "Bez prijave za goste"],
    cta: "Kreiraj galeriju i QR kod →",
    designCta: "Pogledaj dizajne kartica",
    note: (p) => `Tiskani stalci od ${p}/kom · naručite najmanje 10 dana prije događaja`,
    woodName: "Drveni stalak", goldName: "Zlatni stalak", perPiece: " / kom",
    imageAlts: [
      "Guestcam QR kartice za dijeljenje fotografija na događaju",
      "Guestcam galerija fotografija prikazana na telefonu gosta",
      "Zlatni stolni stalak s Guestcam QR kodom",
      "Gost pregledava fotografije događaja u Guestcam galeriji na telefonu",
    ],
    statusPhoto: "Skeniraj i podijeli",
    statusUpload: "Prijenos završen!",
    statusLive: "Slideshow uživo",
    statusNew: "Dodana nova fotografija",
    trustLine: "Stvoreno za stvarne trenutke · Privatno i sigurno",
  },
  sr: {
    badge: "Predlošci za štampu",
    title: "Sačuvajte svaki trenutak.",
    accentTitle: "Proživite ih ponovo.",
    body: "Postavite QR kod na stolove i omogućite gostima da fotografije i video-snimke dele u jednoj prelepoj galeriji.",
    bullets: ["Podešavanje u 3 koraka", "Bez aplikacije", "Besplatna proba", "Bez prijave za goste"],
    cta: "Napravi galeriju i QR kod →",
    designCta: "Pogledaj dizajne kartica",
    note: (p) => `Štampani stalci od ${p}/kom · naručite najmanje 10 dana pre događaja`,
    woodName: "Drveni stalak", goldName: "Zlatni stalak", perPiece: " / kom",
    imageAlts: [
      "Guestcam QR kartice za deljenje fotografija na događaju",
      "Guestcam galerija fotografija prikazana na telefonu gosta",
      "Zlatni stoni stalak sa Guestcam QR kodom",
      "Gost pregleda fotografije događaja u Guestcam galeriji na telefonu",
    ],
    statusPhoto: "Skeniraj i podeli",
    statusUpload: "Otpremanje završeno!",
    statusLive: "Slideshow uživo",
    statusNew: "Dodata nova fotografija",
    trustLine: "Napravljeno za stvarne trenutke · Privatno i sigurno",
  },
  de: {
    badge: "Druckvorlagen",
    title: "Halten Sie jeden Moment fest.",
    accentTitle: "Erleben Sie ihn immer wieder.",
    body: "Stellen Sie den QR-Code auf die Tische und lassen Sie Ihre Gäste Fotos und Videos in einer gemeinsamen, privaten Galerie teilen.",
    bullets: ["Einrichtung in 3 Schritten", "Keine App", "Kostenlos testen", "Keine Anmeldung für Gäste"],
    cta: "Galerie und QR-Code erstellen →",
    designCta: "Kartendesigns ansehen",
    note: (p) => `Gedruckte Aufsteller ab ${p}/Stück · mindestens 10 Tage vor dem Event bestellen`,
    woodName: "Holz-Aufsteller", goldName: "Gold-Aufsteller", perPiece: " / Stück",
    imageAlts: [
      "Guestcam QR-Karten zum Teilen von Eventfotos",
      "Guestcam Fotogalerie auf dem Smartphone eines Gastes",
      "Goldener Tischaufsteller mit Guestcam QR-Code",
      "Gast betrachtet Eventfotos in der Guestcam Galerie auf dem Smartphone",
    ],
    statusPhoto: "Scannen & teilen",
    statusUpload: "Upload abgeschlossen!",
    statusLive: "Live-Slideshow",
    statusNew: "Neues Foto hinzugefügt",
    trustLine: "Für echte Momente gemacht · Privat und sicher",
  },
  en: {
    badge: "Print templates",
    title: "Collect every moment.",
    accentTitle: "Relive them forever.",
    body: "Place your QR code on the tables and let guests share photos and videos into one beautiful private gallery.",
    bullets: ["Set up in 3 steps", "No app", "Free trial", "No guest sign-up"],
    cta: "Create gallery and QR code →",
    designCta: "View card designs",
    note: (p) => `Printed table stands from ${p}/piece · order at least 10 days before the event`,
    woodName: "Wooden stand", goldName: "Gold stand", perPiece: " / piece",
    imageAlts: [
      "Guestcam QR cards for sharing photos at an event",
      "Guestcam photo gallery displayed on a guest's phone",
      "Gold table stand with a Guestcam QR code",
      "Guest viewing event photos in a Guestcam gallery on a phone",
    ],
    statusPhoto: "Scan & share",
    statusUpload: "Upload complete!",
    statusLive: "Live slideshow",
    statusNew: "New photo added",
    trustLine: "Made for real moments · Private and secure",
  },
  es: {
    badge: "Plantillas para imprimir",
    title: "Guarda cada momento.",
    accentTitle: "Vívelos una y otra vez.",
    body: "Coloca el código QR en las mesas y deja que tus invitados compartan fotos y vídeos en una única galería privada.",
    bullets: ["Configuración en 3 pasos", "Sin app", "Prueba gratuita", "Sin registro para invitados"],
    cta: "Crear galería y código QR →",
    designCta: "Ver diseños de tarjetas",
    note: (p) => `Soportes impresos desde ${p}/ud. · pide al menos 10 días antes del evento`,
    woodName: "Soporte de madera", goldName: "Soporte dorado", perPiece: " / ud.",
    imageAlts: [
      "Tarjetas QR de Guestcam para compartir fotos en un evento",
      "Galería de fotos de Guestcam mostrada en el teléfono de un invitado",
      "Soporte de mesa dorado con código QR de Guestcam",
      "Invitado viendo fotos del evento en una galería de Guestcam desde el móvil",
    ],
    statusPhoto: "Escanea y comparte",
    statusUpload: "¡Carga completada!",
    statusLive: "Presentación en directo",
    statusNew: "Nueva foto añadida",
    trustLine: "Creado para momentos reales · Privado y seguro",
  },
};

export const BUSINESS_COPY: Record<SectionLang, BusinessCopy> = {
  sl: {
    badge: "Guestcam za podjetja",
    title: "Naj udeleženci ustvarijo vsebino za vaš dogodek.",
    body: "Za konference, promocije, sejme, športne dogodke, poslovna praznovanja in agencije. Udeleženci nalagajo prek QR kode, vsebine pa lahko prikažete v živo.",
    bullets: ["lastna grafična podoba", "Live Photo Wall", "zbiranje kontaktov ob soglasju", "sponzorski oglasi", "QR upload brez aplikacije", "prenos vseh vsebin"],
    cta: "Ponudba za podjetja →",
    imgAlt: "Poslovni dogodek z uporabo Guestcam QR galerije",
  },
  hr: {
    badge: "Guestcam za tvrtke",
    title: "Neka sudionici stvaraju sadržaj za vaš događaj.",
    body: "Za konferencije, promocije, sajmove, sportske događaje, poslovne proslave i agencije. Sudionici učitavaju putem QR koda, a sadržaj možete prikazati uživo.",
    bullets: ["vlastiti vizualni identitet", "Live Photo Wall", "prikupljanje kontakata uz privolu", "sponzorski oglasi", "QR upload bez aplikacije", "preuzimanje svih sadržaja"],
    cta: "Ponuda za tvrtke →",
    imgAlt: "Poslovni događaj s Guestcam QR galerijom",
  },
  sr: {
    badge: "Guestcam za firme",
    title: "Neka učesnici stvaraju sadržaj za vaš događaj.",
    body: "Za konferencije, promocije, sajmove, sportske događaje, poslovne proslave i agencije. Učesnici otpremaju preko QR koda, a sadržaj možete prikazati uživo.",
    bullets: ["sopstveni vizuelni identitet", "Live Photo Wall", "prikupljanje kontakata uz saglasnost", "sponzorski oglasi", "QR upload bez aplikacije", "preuzimanje svih sadržaja"],
    cta: "Ponuda za firme →",
    imgAlt: "Poslovni događaj sa Guestcam QR galerijom",
  },
  de: {
    badge: "Guestcam für Firmen",
    title: "Lassen Sie die Gäste den Content Ihres Events erstellen.",
    body: "Für Konferenzen, Promotions, Messen, Sportevents, Firmenfeiern und Agenturen. Teilnehmer laden per QR-Code hoch, die Inhalte zeigen Sie live.",
    bullets: ["eigenes Branding", "Live Photo Wall", "Kontakterfassung mit Einwilligung", "Sponsoren-Einblendungen", "QR-Upload ohne App", "Download aller Inhalte"],
    cta: "Angebot für Firmen →",
    imgAlt: "Firmenevent mit Guestcam QR-Galerie",
  },
  en: {
    badge: "Guestcam for business",
    title: "Let attendees create the content of your event.",
    body: "For conferences, promotions, trade shows, sports events, company celebrations and agencies. Attendees upload via QR code and you can show everything live.",
    bullets: ["your own branding", "Live Photo Wall", "consent-based lead capture", "sponsor slides", "QR upload with no app", "download of all content"],
    cta: "Business offer →",
    imgAlt: "Corporate event using a Guestcam QR gallery",
  },
  es: {
    badge: "Guestcam para empresas",
    title: "Deja que los asistentes creen el contenido de tu evento.",
    body: "Para conferencias, promociones, ferias, eventos deportivos, celebraciones de empresa y agencias. Los asistentes suben por código QR y todo se puede mostrar en directo.",
    bullets: ["tu propia imagen de marca", "Live Photo Wall", "captación de contactos con consentimiento", "anuncios de patrocinadores", "subida por QR sin app", "descarga de todo el contenido"],
    cta: "Oferta para empresas →",
    imgAlt: "Evento corporativo con galería QR de Guestcam",
  },
};
