import { SITE_URL } from "@/lib/urls";

/**
 * Single source of truth for CamLove social-share images.
 * The image is generated by app/opengraph-image.tsx so every crawler
 * receives a current CamLove-branded 1200×630 card without stale Guestcam assets.
 */
export const OG_IMAGE_VERSION = 3;
export const OG_IMAGE_URL = `${SITE_URL}/opengraph-image?v=${OG_IMAGE_VERSION}`;
export const OG_IMAGE_WIDTH = 1200;
export const OG_IMAGE_HEIGHT = 630;

export function ogImage(alt: string) {
  return {
    url: OG_IMAGE_URL,
    width: OG_IMAGE_WIDTH,
    height: OG_IMAGE_HEIGHT,
    alt,
    type: "image/png" as const,
  };
}
