"use client";
import { useEffect,useRef,useState } from 'react';
import type { Lang } from '@/lib/i18n/translations';
import { weddingCopy } from '@/lib/wedding/copy';
export function HeroVideo({lang}: {lang:Lang}) {
 const t=weddingCopy(lang);const video=useRef<HTMLVideoElement>(null);const box=useRef<HTMLDivElement>(null);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const [wide,setWide]=useState(false);const [playing,setPlaying]=useState(false);const [started,setStarted]=useState(false);const [controls,setControls]=useState(true);const [muted,setMuted]=useState(false);const [time,setTime]=useState(0);const [duration,setDuration]=useState(0);const [failed,setFailed]=useState(false);
 useEffect(()=>{const mq=matchMedia('(min-width:768px)');const change=()=>setWide(mq.matches);change();mq.addEventListener('change',change);return()=>{mq.removeEventListener('change',change);if(timer.current)clearTimeout(timer.current);};},[]);
 function reveal(){setControls(true);if(timer.current)clearTimeout(timer.current);if(!video.current?.paused)timer.current=setTimeout(()=>{if(!box.current?.contains(document.activeElement))setControls(false);},2200);}
 async function toggle(){const v=video.current;if(!v)return;if(v.paused){if(!v.getAttribute('src')){v.src=wide?'/promo/guestcam-desktop.mp4':'/promo/kako-deluje.mp4';v.load();}try{await v.play();setFailed(false);}catch{setFailed(true);setControls(true);}}else v.pause();}
 function full(){const v=video.current as (HTMLVideoElement&{webkitEnterFullscreen?:()=>void})|null;if(box.current?.requestFullscreen)void box.current.requestFullscreen().catch(()=>{});else v?.webkitEnterFullscreen?.();}
 const format=(n:number)=>`${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`;
 return <figure className="mx-auto w-full max-w-[360px] md:max-w-[1240px]"><div ref={box} className="relative isolate overflow-hidden rounded-[26px] border border-white/20 bg-black shadow-[0_30px_80px_rgba(0,0,0,.20)] sm:rounded-[36px]" onPointerMove={reveal} onFocusCapture={reveal}><video ref={video} playsInline preload="none" poster={wide?'/promo/guestcam-desktop-poster.webp':'/promo/kako-deluje-poster.webp'} className="block aspect-[9/16] w-full bg-black object-contain md:aspect-video" aria-label={t.videoTitle} onClick={()=>void toggle()} onPlay={()=>{setPlaying(true);setStarted(true);reveal();}} onPause={()=>{setPlaying(false);setControls(true);}} onEnded={()=>{setPlaying(false);setControls(true);}} onTimeUpdate={()=>setTime(video.current?.currentTime??0)} onLoadedMetadata={()=>setDuration(video.current?.duration??0)} onError={()=>setFailed(true)}/>{!playing&&<button type="button" aria-label={t.play} onClick={()=>void toggle()} className="absolute inset-0 flex items-center justify-center bg-black/10"><span className="flex size-20 items-center justify-center rounded-full border border-white/50 bg-white/95 pl-1 text-3xl text-black shadow-xl transition hover:scale-105 sm:size-24">▶</span></button>}{started&&<div className={`absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/95 to-transparent px-4 pb-4 pt-12 transition-opacity duration-200 ${controls?'opacity-100':'pointer-events-none opacity-0'}`} onPointerDown={reveal}><div className="flex items-center gap-3 text-white"><button type="button" tabIndex={controls?0:-1} aria-label={playing?t.pause:t.play} className="min-h-11 min-w-9 text-xl" onClick={()=>void toggle()}>{playing?'Ⅱ':'▶'}</button><input aria-label={t.seek} tabIndex={controls?0:-1} type="range" min={0} max={Number.isFinite(duration)?duration:0} step={.1} value={time} className="min-w-0 flex-1 accent-white" onChange={e=>{if(video.current)video.current.currentTime=Number(e.target.value);setTime(Number(e.target.value));reveal();}}/><span className="text-xs tabular-nums">{format(time)}</span><button type="button" tabIndex={controls?0:-1} aria-label={muted?t.unmute:t.mute} onClick={()=>{if(video.current){video.current.muted=!muted;setMuted(!muted);}reveal();}} className="min-h-11 min-w-9">{muted?'🔇':'🔊'}</button><button type="button" tabIndex={controls?0:-1} aria-label={t.fullscreen} onClick={full} className="min-h-11 min-w-9 text-xl">⛶</button></div></div>}{failed&&<p role="alert" className="absolute inset-x-4 top-4 rounded-xl bg-white p-3 text-sm text-red-800">{t.error}</p>}</div><figcaption className="mt-4 text-center text-xs text-stone-500">{t.videoLanguage}</figcaption></figure>;
}
