import Link from 'next/link';
import type { Lang } from '@/lib/i18n/translations';
import { localePublicPath,localizedAccountPath } from '@/lib/urls';
import { WEDDING_PATHS } from '@/lib/wedding/contracts';
import { weddingCopy } from '@/lib/wedding/copy';
import { HeroVideo } from './HeroVideo';
export function HomeWeddingHero({lang,title,accent,lead,start,note}: {lang:Lang;title:string;accent:string;lead:string;start:string;note:string}) {
 const t=weddingCopy(lang);return <section className="relative overflow-hidden border-b border-black/10 bg-[#fffdf8] px-5 pb-14 pt-10 sm:px-8 sm:pb-20 sm:pt-16"><div aria-hidden className="pointer-events-none absolute inset-x-0 top-40 h-[600px] bg-[radial-gradient(ellipse_at_center,rgba(244,180,0,.14),transparent_70%)]"/><div className="relative mx-auto max-w-5xl text-center"><Link href={localePublicPath(lang,WEDDING_PATHS[lang])} className="inline-flex items-center gap-2 rounded-full border border-amber-300 bg-amber-50 px-4 py-2 text-xs font-bold text-amber-950">{t.plan} <span aria-hidden>↗</span></Link><h1 className="mx-auto mt-6 max-w-4xl text-[clamp(2.5rem,6.5vw,5.5rem)] font-black leading-[1.04] tracking-[-.045em]">{title}<span className="block text-[#967000]">{accent}</span></h1><p className="mx-auto mt-5 max-w-2xl text-base leading-7 text-stone-600 sm:text-lg sm:leading-8">{lead}</p><div className="mt-6 flex flex-col justify-center gap-3 sm:flex-row"><Link href={localizedAccountPath(lang,'/dashboard/new')} className="rounded-full bg-[#f4b400] px-7 py-4 text-sm font-black text-black shadow-sm">{start}</Link><Link href={localePublicPath(lang,WEDDING_PATHS[lang])} className="rounded-full border border-stone-300 bg-white px-7 py-4 text-sm font-bold">{t.details} →</Link></div><p className="mb-8 mt-3 text-xs text-stone-500">{note}</p></div><div className="relative"><HeroVideo lang={lang}/></div><div className="relative mx-auto mt-8 flex max-w-3xl flex-wrap justify-center gap-x-6 gap-y-3 text-xs font-bold text-stone-600"><strong>{t.plan}:</strong>{[t.schedule,t.menu,t.songs,t.bingo].map(label=><span key={label}>✓ {label}</span>)}</div></section>;
}
