"use client";
import { useState } from 'react';
import type { Lang } from '@/lib/i18n/translations';
import { weddingCopy,defaultChallenges } from '@/lib/wedding/copy';
import { WeddingPanel,ScheduleView,MenuView,BingoView,SongList,fieldClass,buttonClass } from './WeddingViews';
// The public walkthrough renders the same components as the private wedding UI,
// using explicitly labelled sample content, never real customer album data.
export function WeddingWalkthrough({lang}: {lang:Lang}) {
 const t=weddingCopy(lang);const [tab,setTab]=useState<'organiser'|'guest'|'dj'>('guest');const rows=[{id:'sample-schedule',time:'20:00',title:t.firstDance,detail:''}];const menu=[{id:'starter',title:t.starters,detail:''},{id:'dessert',title:t.dessert,detail:''}];const songs=[{id:'sample-song',title:'Perfect',artist:'Ed Sheeran',requestedBy:'Ana',note:'',status:'new' as const,createdAt:'2026-09-26T00:00:00Z'}];
 return <div className="overflow-hidden rounded-[30px] border border-stone-200 bg-stone-100 shadow-xl"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-stone-200 bg-white px-4 py-4 sm:px-7"><p className="text-xs font-bold uppercase tracking-widest text-stone-500">GuestCam · {t.preview}</p><div className="flex max-w-full gap-1 rounded-xl bg-stone-100 p-1" role="group" aria-label={t.preview}>{(['organiser','guest','dj'] as const).map(key=><button key={key} className={`min-h-10 rounded-lg px-3 text-xs font-bold transition sm:px-5 ${tab===key?'bg-stone-900 text-white':'text-stone-600'}`} aria-pressed={tab===key} onClick={()=>setTab(key)}>{t[key]}</button>)}</div></div><div className="p-4 sm:p-8"><p className="mb-5 text-center text-xs text-stone-500">{t.sample}</p>{tab==='guest'?<div className="space-y-5"><div className="rounded-2xl bg-stone-900 px-6 py-7 text-center text-white"><p className="text-xs uppercase tracking-widest text-amber-300">{t.guest}</p><h3 className="mt-3 font-serif text-3xl">Ana & Marko</h3></div><div className="grid gap-4 sm:grid-cols-2"><WeddingPanel title={t.schedule}><ScheduleView rows={rows} lang={lang}/></WeddingPanel><WeddingPanel title={t.menu}><MenuView rows={menu} lang={lang}/></WeddingPanel></div><WeddingPanel title={t.bingo}><BingoView rows={defaultChallenges(lang).slice(0,6)} lang={lang} preview/></WeddingPanel></div>:tab==='dj'?<WeddingPanel title={t.dj}><SongList lang={lang} songs={songs} onStatus={()=>{}} disabled/></WeddingPanel>:<WeddingPanel title={t.plan} badge={t.organiser}><div className="space-y-5"><label className="flex gap-3 rounded-xl bg-amber-50 p-4 text-sm font-bold"><input type="checkbox" checked readOnly disabled/>{t.enabled}</label><h3 className="font-semibold">{t.schedule}</h3><div className="grid gap-3 sm:grid-cols-[110px_1fr]"><label className="text-xs font-semibold">{t.time}<input className={`${fieldClass} mt-2`} value="20:00" readOnly/></label><label className="text-xs font-semibold">{t.rowTitle}<input className={`${fieldClass} mt-2`} value={t.firstDance} readOnly/></label></div><h3 className="font-semibold">{t.menu}</h3><MenuView rows={menu} lang={lang}/><button className={buttonClass} disabled>{t.save}</button></div></WeddingPanel>}</div></div>;
}
