"use client";
import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { LANGS, type Lang } from '@/lib/i18n/translations';
import { weddingCopy, weddingError } from '@/lib/wedding/copy';
import { type WeddingGuestData, type WeddingRow } from '@/lib/wedding/contracts';
import { UploadModal } from '@/components/album/UploadModal';
import { WeddingPanel, ScheduleView, MenuView, BingoView, SongList, fieldClass, buttonClass, secondaryClass } from './WeddingViews';
export function WeddingGuest({slug,initialLang}: {slug:string;initialLang:Lang}) {
 const [lang,setLang]=useState(initialLang);const t=weddingCopy(lang);const [data,setData]=useState<WeddingGuestData|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [sent,setSent]=useState(false);const [name,setName]=useState('');const [challenge,setChallenge]=useState<WeddingRow|null>(null);const [upload,setUpload]=useState(false);
 const endpoint=`/api/albums/${encodeURIComponent(slug)}/wedding`;
 const load=useCallback(async()=>{setError('');try{const r=await fetch(endpoint,{cache:'no-store'});const d=await r.json();if(!r.ok){setData(null);throw new Error(d.error);}setData(d);}catch(e){setError(weddingError(lang,e instanceof Error?e.message:''));}finally{setLoading(false);}},[endpoint,lang]);
 useEffect(()=>{void load();},[load]);
 async function requestSong(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const values=new FormData(form);setBusy(true);setSent(false);setError('');try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:values.get('title'),artist:values.get('artist'),requestedBy:values.get('requestedBy'),note:values.get('note')})});const d=await r.json();if(!r.ok)throw new Error(d.error);form.reset();setSent(true);await load();}catch(e){setError(weddingError(lang,e instanceof Error?e.message:''));}finally{setBusy(false);}}
 return <main className="min-h-screen bg-[#fcfaf6] px-4 py-6 text-stone-900 sm:px-6 sm:py-10"><div className="mx-auto max-w-4xl"><header className="mb-6 flex flex-wrap items-center justify-between gap-3"><a href={`/${encodeURIComponent(slug)}?lang=${lang}`} className={secondaryClass}>← {t.gallery}</a><label className="text-xs font-medium">{t.language}<select className="ml-2 min-h-11 rounded-xl border border-stone-200 bg-white px-3 text-sm" value={lang} onChange={e=>setLang(e.target.value as Lang)}>{LANGS.map(l=><option key={l.code} value={l.code}>{l.native}</option>)}</select></label></header><div className="mb-8 rounded-3xl bg-stone-900 px-6 py-9 text-white sm:px-10"><p className="text-xs font-semibold uppercase tracking-[.22em] text-amber-300">GuestCam · {t.guest}</p><h1 className="mt-4 break-words font-serif text-4xl sm:text-5xl">{data?.name??t.nav}</h1>{data?.date&&<p className="mt-3 text-sm text-stone-300">{new Intl.DateTimeFormat(lang,{dateStyle:'long',timeZone:'UTC'}).format(new Date(`${data.date.slice(0,10)}T12:00:00Z`))}</p>}<p className="mt-4 max-w-xl text-sm leading-6 text-stone-300">{t.subtitle}</p></div>{loading&&<p role="status">{t.loading}</p>}{error&&<div role="alert" className="mb-5 rounded-2xl bg-red-50 p-5 text-red-800">{error}<button className="ml-3 underline" onClick={()=>void load()}>{t.refresh}</button></div>}
 {data&&<div className="space-y-6"><div className="grid gap-6 md:grid-cols-2"><WeddingPanel title={t.schedule}><ScheduleView rows={data.schedule} lang={lang}/></WeddingPanel><WeddingPanel title={t.menu}><MenuView rows={data.menu} lang={lang}/></WeddingPanel></div><WeddingPanel title={t.songs}><p className="mb-5 text-sm leading-6 text-stone-600">{t.songHint}</p>{data.requestsOpen?<form onSubmit={requestSong} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium">{t.titleField}<input name="title" required maxLength={160} className={`${fieldClass} mt-1`}/></label><label className="block text-sm font-medium">{t.artist}<input name="artist" maxLength={160} className={`${fieldClass} mt-1`}/></label></div><label className="block text-sm font-medium">{t.name}<input name="requestedBy" required maxLength={80} defaultValue={name} onChange={e=>setName(e.target.value)} autoComplete="given-name" className={`${fieldClass} mt-1`}/></label><label className="block text-sm font-medium">{t.note}<textarea name="note" maxLength={500} rows={2} className={`${fieldClass} mt-1`}/></label><button className={buttonClass} disabled={busy}>{busy?t.saving:t.send}</button>{sent&&<p role="status" className="text-sm text-emerald-700">{t.sent}</p>}</form>:<p className="rounded-xl bg-amber-50 p-4 text-sm text-amber-900">{t.requestsPaused}</p>}{data.myRequests.length>0&&<div className="mt-6 border-t border-stone-100 pt-5"><h3 className="mb-3 text-sm font-bold">{t.mine}</h3><SongList songs={data.myRequests} lang={lang}/></div>}</WeddingPanel><WeddingPanel title={t.bingo}><p className="mb-5 text-sm leading-6 text-stone-600">{t.bingoHint}</p><BingoView rows={data.challenges} lang={lang} latestPhotos={data.latestPhotos} completed={data.completed} mine={data.mine} onUpload={data.allowBingoUpload?(row)=>{setChallenge(row);setUpload(false);}:undefined}/>{data.moderationEnabled&&<p className="mt-4 text-xs leading-5 text-stone-500">{t.pendingNote}</p>}<button className={`${secondaryClass} mt-5`} onClick={()=>void load()}>{t.refresh}</button></WeddingPanel></div>}
 <footer className="py-8 text-center text-xs text-stone-400">GuestCam · {t.guest}</footer></div>
 {challenge&&!upload&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" onClick={()=>setChallenge(null)}><form onSubmit={e=>{e.preventDefault();if(name.trim())setUpload(true);}} onClick={e=>e.stopPropagation()} role="dialog" aria-modal="true" aria-labelledby="bingo-upload-title" className="w-full max-w-md space-y-4 rounded-3xl bg-white p-6"><h2 id="bingo-upload-title" className="text-xl font-bold">{challenge.title}</h2><label className="block text-sm font-medium">{t.name}<input autoFocus required maxLength={80} value={name} onChange={e=>setName(e.target.value)} className={`${fieldClass} mt-2`}/></label><div className="flex flex-wrap gap-3"><button className={buttonClass} disabled={!name.trim()}>{t.upload}</button><button type="button" className={secondaryClass} onClick={()=>setChallenge(null)}>{t.cancel}</button></div></form></div>}
 {data&&challenge&&upload&&<UploadModal albumSlug={slug} albumId={data.albumId} uploaderName={name.trim()} maxPhotos={data.maxPhotos} currentCount={data.photoCount} lang={lang} bingoChallengeId={challenge.id} requireGuestData={data.requireGuestData} organiserName={data.name} moderationEnabled={data.moderationEnabled} onClose={()=>{setUpload(false);setChallenge(null);void load();}} onSuccess={()=>{setUpload(false);setChallenge(null);void load();}}/>}
 </main>;
}
