"use client";
import type { ReactNode } from 'react';
import type { Lang } from '@/lib/i18n/translations';
import { weddingCopy } from '@/lib/wedding/copy';
import type { WeddingRow, WeddingSong, SongStatus } from '@/lib/wedding/contracts';
export const fieldClass = 'w-full min-w-0 rounded-xl border border-stone-300 bg-white px-3 py-3 text-base text-stone-900 focus:border-amber-600 focus:outline-none focus:ring-2 focus:ring-amber-500/20';
export const buttonClass = 'inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-stone-900 px-5 py-3 text-sm font-bold text-white transition hover:bg-stone-700 disabled:cursor-not-allowed disabled:opacity-50';
export const secondaryClass = 'inline-flex min-h-11 items-center justify-center rounded-xl border border-stone-300 bg-white px-4 py-2 text-sm font-semibold text-stone-800 hover:bg-amber-50 disabled:opacity-50';
export function WeddingPanel({title, children, badge}: {title: string; children: ReactNode; badge?: string}) { return <section className="min-w-0 rounded-3xl border border-stone-200 bg-white p-5 shadow-sm sm:p-7"><div className="mb-5 flex flex-wrap items-center justify-between gap-2"><h2 className="text-xl font-bold tracking-tight text-stone-900">{title}</h2>{badge && <span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-semibold text-amber-900">{badge}</span>}</div>{children}</section>; }
export function ScheduleView({rows, lang}: {rows: WeddingRow[]; lang: Lang}) { const t=weddingCopy(lang); return rows.length ? <ol className="space-y-5">{rows.map(row=><li key={row.id} className="flex gap-4"><time className="w-14 shrink-0 pt-1 text-sm font-bold text-amber-800">{row.time ?? '—'}</time><div className="min-w-0 border-l-2 border-amber-200 pl-5"><h3 className="break-words font-semibold text-stone-900">{row.title}</h3>{row.detail && <p className="mt-1 whitespace-pre-wrap break-words text-sm leading-6 text-stone-600">{row.detail}</p>}</div></li>)}</ol> : <p className="text-sm text-stone-500">{t.scheduleEmpty}</p>; }
export function MenuView({rows, lang}: {rows: WeddingRow[]; lang: Lang}) { const t=weddingCopy(lang); return rows.length ? <div className="divide-y divide-stone-100">{rows.map(row=><article key={row.id} className="py-4 first:pt-0"><h3 className="break-words font-serif text-xl text-stone-900">{row.title}</h3>{row.detail && <p className="mt-2 whitespace-pre-wrap break-words text-sm leading-6 text-stone-600">{row.detail}</p>}</article>)}</div> : <p className="text-sm text-stone-500">{t.menuEmpty}</p>; }
export function BingoView({rows,lang,completed={},mine={},latestPhotos={},onUpload,preview=false}: {rows: WeddingRow[];lang: Lang;completed?:Record<string,number>;latestPhotos?:Record<string,string>;mine?:Record<string,number>;onUpload?:(row:WeddingRow)=>void;preview?:boolean}) { const t=weddingCopy(lang); if (!rows.length) return <p className="text-sm text-stone-500">{t.bingoEmpty}</p>; return <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{rows.map((row,i)=><article key={row.id} className={`flex min-h-40 min-w-0 flex-col rounded-2xl border p-3 sm:p-4 ${mine[row.id] ? 'border-emerald-300 bg-emerald-50' : 'border-amber-200 bg-amber-50/60'}`}><span className="text-xs font-bold text-amber-800">{mine[row.id] ? '✓' : String(i+1).padStart(2,'0')}</span><h3 className="mt-2 break-words text-sm font-bold leading-5 text-stone-900">{row.title}</h3>{latestPhotos[row.id] && <img src={latestPhotos[row.id]} alt={row.title} loading="lazy" width={240} height={180} className="mt-3 aspect-[4/3] w-full rounded-lg object-cover"/>}{row.detail && <p className="mt-2 break-words text-xs leading-5 text-stone-600">{row.detail}</p>}<p className="mb-3 mt-2 text-xs text-stone-500">{t.completed}: {completed[row.id]??0}</p>{onUpload || preview ? <button type="button" disabled={preview} onClick={()=>onUpload?.(row)} className="mt-auto min-h-10 rounded-lg bg-white px-2 py-2 text-xs font-bold text-stone-900 ring-1 ring-stone-200 disabled:opacity-60">{t.upload}</button> : null}</article>)}</div>; }
export function SongList({songs,lang,onStatus,disabled=false}: {songs:WeddingSong[];lang:Lang;onStatus?:(id:string,status:SongStatus)=>void;disabled?:boolean}) { const t=weddingCopy(lang); return songs.length ? <div className="space-y-3">{songs.map(song=><article key={song.id} className="min-w-0 rounded-2xl border border-stone-200 bg-stone-50 p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div className="min-w-0"><h3 className="break-words font-bold text-stone-900">{song.title}</h3><p className="break-words text-sm text-stone-600">{song.artist}</p></div><span className="rounded-full bg-white px-3 py-1 text-xs font-semibold text-stone-600">{t[song.status]}</span></div><p className="mt-2 break-words text-xs text-stone-500">{song.requestedBy}</p>{song.note && <p className="mt-2 break-words text-sm text-stone-600">{song.note}</p>}{onStatus && <label className="mt-3 block text-xs font-semibold text-stone-600">{t.status}<select className={`${fieldClass} mt-1`} value={song.status} disabled={disabled} onChange={e=>onStatus(song.id,e.target.value as SongStatus)}>{(['new','accepted','played','declined'] as SongStatus[]).map(status=><option key={status} value={status}>{t[status]}</option>)}</select></label>}</article>)}</div> : <p className="text-sm text-stone-500">{t.noSongs}</p>; }
