"use client";
import { useCallback, useEffect, useState } from 'react';
import type { Lang } from '@/lib/i18n/translations';
import { weddingCopy, weddingError, defaultChallenges } from '@/lib/wedding/copy';
import { EMPTY_WEDDING, type WeddingRow, type WeddingSettings } from '@/lib/wedding/contracts';
import { WeddingPanel, fieldClass, buttonClass, secondaryClass, ScheduleView, MenuView, BingoView } from './WeddingViews';
type Group='schedule'|'menu'|'challenges';
export function WeddingSettingsCard({slug,lang,plan}: {slug:string;lang:Lang;plan:string}) {
 const t=weddingCopy(lang);const [data,setData]=useState<WeddingSettings>(EMPTY_WEDDING);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');const [published,setPublished]=useState(false);const [eligible,setEligible]=useState(plan==='premium');const [hasDj,setHasDj]=useState(false);const [djLink,setDjLink]=useState('');const [guestLink,setGuestLink]=useState('');const [preview,setPreview]=useState(false);
 const endpoint=`/api/albums/${encodeURIComponent(slug)}/wedding/manage`;
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await fetch(endpoint,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d.settings);setPublished(d.published);setEligible(d.eligible);setHasDj(d.hasDjLink);}catch(e){setError(weddingError(lang,e instanceof Error?e.message:''));}finally{setLoading(false);}},[endpoint,lang]);
 useEffect(()=>{void load();setGuestLink(`${location.origin}/${encodeURIComponent(slug)}/wedding?lang=${lang}`);},[load,slug,lang]);
 const edit=(group:Group,id:string,key:keyof WeddingRow,value:string)=>setData(d=>({...d,[group]:d[group].map(row=>row.id===id?{...row,[key]:value}:row)}));
 const add=(group:Group)=>setData(d=>({...d,[group]:[...d[group],{id:crypto.randomUUID(),title:'',detail:'',...(group==='schedule'?{time:'18:00'}:{})}]}));
 async function save(){setSaving(true);setError('');setMessage('');try{const r=await fetch(endpoint,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d.settings);setMessage(t.saved);}catch(e){setError(weddingError(lang,e instanceof Error?e.message:''));}finally{setSaving(false);}}
 async function dj(){if(hasDj&&!window.confirm(t.rotateConfirm))return;setSaving(true);setError('');try{const r=await fetch(endpoint,{method:'POST'});const d=await r.json();if(!r.ok)throw new Error(d.error);const u=new URL(d.path,location.origin);u.searchParams.set('lang',lang);setDjLink(u.href);setHasDj(true);}catch(e){setError(weddingError(lang,e instanceof Error?e.message:''));}finally{setSaving(false);}}
 async function copy(value:string){try{await navigator.clipboard.writeText(value);setMessage(t.copied);}catch{setError(t.error);}}
 return <div className="space-y-5" id="wedding-settings"><WeddingPanel title={t.plan} badge={t.organiser}><p className="mb-5 text-sm leading-6 text-stone-600">{t.setupHint}</p>{error&&<div role="alert" className="mb-4 rounded-xl bg-red-50 p-4 text-sm text-red-800">{error}<button className="ml-3 underline" onClick={()=>void load()}>{t.refresh}</button></div>}{loading?<p role="status">{t.loading}</p>:!eligible?<p className="rounded-xl bg-amber-50 p-4 text-sm text-amber-900">{t.premiumRequired}</p>:<><label className="flex items-start gap-3 rounded-xl bg-amber-50 p-4"><input type="checkbox" checked={data.enabled} onChange={e=>setData({...data,enabled:e.target.checked})} className="mt-1 size-5"/><span><strong className="block text-sm">{t.enabled}</strong><span className="mt-1 block text-xs leading-5 text-stone-600">{t.enableHint}</span></span></label>{!published&&<p className="mt-3 text-sm text-amber-800">{t.notPublished}</p>}<div className="mt-5 flex flex-wrap gap-3"><button className={buttonClass} onClick={()=>void save()} disabled={saving}>{saving?t.saving:t.save}</button><button className={secondaryClass} onClick={()=>setPreview(!preview)} aria-pressed={preview}>{t.preview}</button>{data.enabled&&published&&<a className={secondaryClass} href={guestLink} target="_blank" rel="noreferrer">{t.guestLink} ↗</a>}</div><p role="status" aria-live="polite" className="mt-3 text-sm text-emerald-700">{message}</p></>}</WeddingPanel>
 {!loading&&eligible&&<>{(['schedule','menu','challenges'] as Group[]).map(group=><WeddingPanel key={group} title={group==='challenges'?t.bingo:t[group]}>{preview ? group==='schedule'?<ScheduleView rows={data.schedule} lang={lang}/>:group==='menu'?<MenuView rows={data.menu} lang={lang}/>:<BingoView rows={data.challenges} lang={lang} preview/> : <><p className="mb-4 text-sm leading-6 text-stone-500">{group==='menu'?t.menuHint:group==='challenges'?t.bingoHint:t.setupHint}</p><div className="space-y-4">{data[group].map((row,i)=><div key={row.id} className="space-y-3 rounded-2xl border border-stone-200 p-4"><div className="flex items-center justify-between"><span className="text-xs font-bold text-stone-400">{i+1}</span><button type="button" onClick={()=>setData(d=>({...d,[group]:d[group].filter(r=>r.id!==row.id)}))} className="min-h-10 px-2 text-sm text-red-700">{t.remove}</button></div>{group==='schedule'&&<label className="block text-xs font-semibold">{t.time}<input type="time" required value={row.time??''} onChange={e=>edit(group,row.id,'time',e.target.value)} className={`${fieldClass} mt-1`}/></label>}<label className="block text-xs font-semibold">{t.rowTitle}<input required maxLength={160} value={row.title} onChange={e=>edit(group,row.id,'title',e.target.value)} className={`${fieldClass} mt-1`}/></label><label className="block text-xs font-semibold">{t.rowDetail}<textarea maxLength={1000} rows={2} value={row.detail} onChange={e=>edit(group,row.id,'detail',e.target.value)} className={`${fieldClass} mt-1`}/></label></div>)}</div><div className="mt-4 flex flex-wrap gap-3"><button type="button" className={secondaryClass} disabled={data[group].length>=(group==='challenges'?25:40)} onClick={()=>add(group)}>+ {t.add}</button>{group==='challenges'&&!data.challenges.length&&<button className={secondaryClass} onClick={()=>setData(d=>({...d,challenges:defaultChallenges(lang)}))}>{t.photoBingoFeatured}</button>}</div></>}</WeddingPanel>)}<WeddingPanel title={t.dj}><p className="text-sm leading-6 text-stone-600">{t.djHelp}</p><label className="my-5 flex items-center gap-3 text-sm font-semibold"><input type="checkbox" className="size-5" checked={data.requestsOpen} onChange={e=>setData({...data,requestsOpen:e.target.checked})}/>{t.requestsOpen}</label><button className={secondaryClass} disabled={saving} onClick={()=>void dj()}>{t.createDj}</button>{djLink&&<div className="mt-4"><input readOnly aria-label={t.dj} value={djLink} className={fieldClass} onFocus={e=>e.target.select()}/><button className={`${secondaryClass} mt-2`} onClick={()=>void copy(djLink)}>{t.copy}</button></div>}</WeddingPanel><div className="sticky bottom-3 z-10 rounded-2xl border border-stone-200 bg-white/95 p-3 shadow-lg backdrop-blur"><button className={`${buttonClass} w-full`} onClick={()=>void save()} disabled={saving}>{saving?t.saving:t.save}</button></div></>}
 </div>;
}
