"use client";
import { useCallback, useEffect, useState } from 'react';
import { LANGS, type Lang } from '@/lib/i18n/translations';
import { weddingCopy,weddingError } from '@/lib/wedding/copy';
import type { WeddingSong, SongStatus } from '@/lib/wedding/contracts';
import { SongList, WeddingPanel, secondaryClass } from './WeddingViews';
export function WeddingDj({slug,initialLang}: {slug:string;initialLang:Lang}) {
 const [lang,setLang]=useState(initialLang);const t=weddingCopy(lang);const [token,setToken]=useState<string|null>(null);const [ready,setReady]=useState(false);const [data,setData]=useState<{name:string;songs:WeddingSong[];requestsOpen:boolean}|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [auto,setAuto]=useState(false);
 const endpoint=`/api/albums/${encodeURIComponent(slug)}/wedding/dj`;
 useEffect(()=>{const key=`gc-wedding-dj:${slug}`;const hash=new URLSearchParams(location.hash.slice(1));let value=hash.get('token');try{if(value&&/^[\w-]{43}$/.test(value)){sessionStorage.setItem(key,value);history.replaceState(null,'',location.pathname+location.search);}else value=sessionStorage.getItem(key);}catch{/* session storage may be disabled; current link still works */}setToken(value&&/^[\w-]{43}$/.test(value)?value:null);setReady(true);},[slug]);
 const load=useCallback(async()=>{if(!token)return;try{const r=await fetch(endpoint,{cache:'no-store',headers:{Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok){setData(null);if(r.status===403)setAuto(false);throw new Error(d.error);}setData(d);setError('');}catch(e){setError(weddingError(lang,e instanceof Error?e.message:''));}},[endpoint,token,lang]);
 useEffect(()=>{void load();},[load]);
 // Poll only after the DJ explicitly opts in, and only while this tab is visible.
 useEffect(()=>{if(!auto||!token)return;const timer=setInterval(()=>{if(!document.hidden)void load();},10_000);return()=>clearInterval(timer);},[auto,token,load]);
 async function update(id:string,status:SongStatus){if(!token)return;setBusy(true);try{const r=await fetch(endpoint,{method:'PATCH',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({id,status})});const d=await r.json();if(!r.ok)throw new Error(d.error);await load();}catch(e){setError(weddingError(lang,e instanceof Error?e.message:''));}finally{setBusy(false);}}
 return <main className="min-h-screen bg-stone-950 px-4 py-6 sm:px-6"><div className="mx-auto max-w-3xl"><header className="mb-8 flex flex-wrap items-start justify-between gap-5 text-white"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-amber-300">GuestCam</p><h1 className="mt-3 text-3xl font-bold">{t.dj}</h1><p className="mt-2 break-words text-stone-400">{data?.name}</p></div><label className="text-xs">{t.language}<select className="ml-2 min-h-11 rounded-xl bg-stone-800 px-3 text-sm" value={lang} onChange={e=>setLang(e.target.value as Lang)}>{LANGS.map(l=><option key={l.code} value={l.code}>{l.native}</option>)}</select></label></header>{(!ready)&&<p className="text-white">{t.loading}</p>}{ready&&!token&&<p role="alert" className="rounded-2xl bg-red-50 p-5 text-red-800">{t.invalidDjLink}</p>}{error&&<p role="alert" className="mb-5 rounded-2xl bg-red-50 p-5 text-red-800">{error}</p>}{token&&<WeddingPanel title={t.songs}><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><button className={secondaryClass} onClick={()=>void load()}>{t.refresh}</button><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)} className="size-5"/>{t.autoRefresh}</label></div>{data&&!data.requestsOpen&&<p className="mb-4 text-sm text-amber-800">{t.requestsPaused}</p>}<SongList songs={data?.songs??[]} lang={lang} onStatus={(id,status)=>void update(id,status)} disabled={busy}/></WeddingPanel>}</div></main>;
}
